
var b;b||(b=typeof Module !== 'undefined' ? Module : {});var ba=Object.assign,ca=ba({},b),h="./this.program";function m(a,c){throw c;}var da="object"===typeof window,n="function"===typeof importScripts,r="",t,u,v,fs,w,x;
if("object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)r=n?require("path").dirname(r)+"/":__dirname+"/",x=function(){fs||(fs=require("fs"),w=require("path"))},t=function(a,c){x();a=w.normalize(a);return fs.readFileSync(a,c?null:"utf8")},v=function(a){a=t(a,!0);a.buffer||(a=new Uint8Array(a));return a},u=function(a,c,d){x();a=w.normalize(a);fs.readFile(a,function(e,g){e?d(e):c(g.buffer)})},1<process.argv.length&&(h=process.argv[1].replace(/\\/g,"/")),
process.argv.slice(2),"undefined"!==typeof module&&(module.exports=b),process.on("uncaughtException",function(a){if(!(a instanceof A))throw a;}),process.on("unhandledRejection",function(a){throw a;}),m=function(a,c){if(noExitRuntime||0<B)throw process.exitCode=a,c;c instanceof A||C("exiting due to exception: "+c);process.exit(a)},b.inspect=function(){return"[Emscripten Module object]"};else if(da||n)n?r=self.location.href:"undefined"!==typeof document&&document.currentScript&&(r=document.currentScript.src),
r=0!==r.indexOf("blob:")?r.substr(0,r.replace(/[?#].*/,"").lastIndexOf("/")+1):"",t=function(a){var c=new XMLHttpRequest;c.open("GET",a,!1);c.send(null);return c.responseText},n&&(v=function(a){var c=new XMLHttpRequest;c.open("GET",a,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)}),u=function(a,c,d){var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=function(){200==e.status||0==e.status&&e.response?c(e.response):d()};e.onerror=d;e.send(null)};
var ea=b.print||console.log.bind(console),C=b.printErr||console.warn.bind(console);ba(b,ca);ca=null;b.thisProgram&&(h=b.thisProgram);b.quit&&(m=b.quit);var E;b.wasmBinary&&(E=b.wasmBinary);var noExitRuntime=b.noExitRuntime||!0;"object"!==typeof WebAssembly&&F("no native wasm support detected");var fa,G=!1,ha="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0,H,I,J,ia,ja=[],ka=[],la=[],ma=!1,B=0;function na(){var a=b.preRun.shift();ja.unshift(a)}var K=0,M=null,N=null;
b.preloadedImages={};b.preloadedAudios={};function F(a){if(b.onAbort)b.onAbort(a);a="Aborted("+a+")";C(a);G=!0;throw new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");}function oa(){return O.startsWith("data:application/octet-stream;base64,")}var O;O="quantsmooth.wasm";if(!oa()){var pa=O;O=b.locateFile?b.locateFile(pa,r):r+pa}
function qa(){var a=O;try{if(a==O&&E)return new Uint8Array(E);if(v)return v(a);throw"both async and sync fetching of the wasm failed";}catch(c){F(c)}}
function ra(){if(!E&&(da||n)){if("function"===typeof fetch&&!O.startsWith("file://"))return fetch(O,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+O+"'";return a.arrayBuffer()}).catch(function(){return qa()});if(u)return new Promise(function(a,c){u(O,function(d){a(new Uint8Array(d))},c)})}return Promise.resolve().then(function(){return qa()})}var sa={9707:function(){setTimeout(b.wasm_return,0)}};
function P(a){for(;0<a.length;){var c=a.shift();if("function"==typeof c)c(b);else{var d=c.C;"number"===typeof d?void 0===c.A?dynCall_v.call(null,d):dynCall_vi.apply(null,[d,c.A]):d(void 0===c.A?null:c.A)}}}var Q=[];function ta(a){if(!ma&&!G)try{a()}catch(c){c instanceof A||"unwind"==c||m(1,c)}}function ua(a,c){setTimeout(function(){ta(a)},c)}var R={};
function va(){if(!S){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:h||"./this.program"},c;for(c in R)void 0===R[c]?delete a[c]:a[c]=R[c];var d=[];for(c in a)d.push(c+"="+a[c]);S=d}return S}var S,wa=[null,[],[]];function T(a){try{a()}catch(c){F(c)}}var U=0,V=null,W=[],xa={},za={},Aa=0,Ba=null,Ca=[];
function Da(a){var c={},d;for(d in a)(function(e){var g=a[e];c[e]="function"===typeof g?function(){W.push(e);try{return g.apply(null,arguments)}finally{G||(W.pop()===e||F(void 0),V&&1===U&&0===W.length&&(U=0,T(b._asyncify_stop_unwind),"undefined"!==typeof Fibers&&Fibers.D()))}}:g})(d);return c}function Ea(){var a=Fa(4108),c=a+12;J[a>>2]=c;J[a+4>>2]=c+4096;c=W[0];var d=xa[c];void 0===d&&(d=Aa++,xa[c]=d,za[d]=c);J[a+8>>2]=d;return a}
function Ga(a){if(!G)if(0===U){var c=!1,d=!1;a(function(){if(!G&&(c=!0,d)){U=2;T(function(){b._asyncify_start_rewind(V)});"undefined"!==typeof Browser&&Browser.B.C&&Browser.B.resume();var e=!1;try{var g=(0,b.asm[za[J[V+8>>2]]])()}catch(L){g=L,e=!0}var f=!1;if(!V){var k=Ba;k&&(Ba=null,(e?k.reject:k.resolve)(g),f=!0)}if(e&&!f)throw g;}});d=!0;c||(U=1,V=Ea(),T(function(){b._asyncify_start_unwind(V)}),"undefined"!==typeof Browser&&Browser.B.C&&Browser.B.pause())}else 2===U?(U=0,T(b._asyncify_stop_rewind),
Ha(V),V=null,Ca.forEach(function(e){ta(e)})):F("invalid state: "+U)}
var Ia={l:function(a,c,d){Q.length=0;var e;for(d>>=2;e=I[c++];)(e=105>e)&&d&1&&d++,Q.push(e?ia[d++>>1]:J[d]),++d;return sa[a].apply(null,Q)},k:function(a,c,d){I.copyWithin(a,c,c+d)},e:function(){F("OOM")},c:function(a){Ga(function(c){ua(c,a)})},f:function(a,c){var d=0;va().forEach(function(e,g){var f=c+d;g=J[a+4*g>>2]=f;for(f=0;f<e.length;++f)H[g++>>0]=e.charCodeAt(f);H[g>>0]=0;d+=e.length+1});return 0},g:function(a,c){var d=va();J[a>>2]=d.length;var e=0;d.forEach(function(g){e+=g.length+1});J[c>>
2]=e;return 0},i:function(a){noExitRuntime||0<B||(ma=!0);if(!(noExitRuntime||0<B)){if(b.onExit)b.onExit(a);G=!0}m(a,new A(a))},h:function(){return 0},j:function(){},a:function(a,c,d,e){for(var g=0,f=0;f<d;f++){var k=J[c>>2],L=J[c+4>>2];c+=8;for(var Y=0;Y<L;Y++){var D=I[k+Y],Z=wa[a];if(0===D||10===D){D=1===a?ea:C;var p=Z;for(var q=0,y=q+NaN,z=q;p[z]&&!(z>=y);)++z;if(16<z-q&&p.subarray&&ha)p=ha.decode(p.subarray(q,z));else{for(y="";q<z;){var l=p[q++];if(l&128){var aa=p[q++]&63;if(192==(l&224))y+=String.fromCharCode((l&
31)<<6|aa);else{var ya=p[q++]&63;l=224==(l&240)?(l&15)<<12|aa<<6|ya:(l&7)<<18|aa<<12|ya<<6|p[q++]&63;65536>l?y+=String.fromCharCode(l):(l-=65536,y+=String.fromCharCode(55296|l>>10,56320|l&1023))}}else y+=String.fromCharCode(l)}p=y}D(p);Z.length=0}else Z.push(D)}g+=L}J[e>>2]=g;return 0},b:function(a){var c=Date.now();J[a>>2]=c/1E3|0;J[a+4>>2]=c%1E3*1E3|0;return 0},d:function(a){b.wasm_progress(a)}};
(function(){function a(f){f=f.exports;f=Da(f);b.asm=f;fa=b.asm.m;f=fa.buffer;b.HEAP8=H=new Int8Array(f);b.HEAP16=new Int16Array(f);b.HEAP32=J=new Int32Array(f);b.HEAPU8=I=new Uint8Array(f);b.HEAPU16=new Uint16Array(f);b.HEAPU32=new Uint32Array(f);b.HEAPF32=new Float32Array(f);b.HEAPF64=ia=new Float64Array(f);ka.unshift(b.asm.n);K--;b.monitorRunDependencies&&b.monitorRunDependencies(K);0==K&&(null!==M&&(clearInterval(M),M=null),N&&(f=N,N=null,f()))}function c(f){a(f.instance)}function d(f){return ra().then(function(k){return WebAssembly.instantiate(k,
e)}).then(function(k){return k}).then(f,function(k){C("failed to asynchronously prepare wasm: "+k);F(k)})}var e={a:Ia};K++;b.monitorRunDependencies&&b.monitorRunDependencies(K);if(b.instantiateWasm)try{var g=b.instantiateWasm(e,a);return g=Da(g)}catch(f){return C("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return E||"function"!==typeof WebAssembly.instantiateStreaming||oa()||O.startsWith("file://")||"function"!==typeof fetch?d(c):fetch(O,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,
e).then(c,function(k){C("wasm streaming compile failed: "+k);C("falling back to ArrayBuffer instantiation");return d(c)})})})();return{}})();b.___wasm_call_ctors=function(){return(b.___wasm_call_ctors=b.asm.n).apply(null,arguments)};b._web_main=function(){return(b._web_main=b.asm.o).apply(null,arguments)};
var Fa=b._malloc=function(){return(Fa=b._malloc=b.asm.p).apply(null,arguments)},Ha=b._free=function(){return(Ha=b._free=b.asm.q).apply(null,arguments)},dynCall_vi=b.dynCall_vi=function(){return(dynCall_vi=b.dynCall_vi=b.asm.s).apply(null,arguments)};b._asyncify_start_unwind=function(){return(b._asyncify_start_unwind=b.asm.t).apply(null,arguments)};b._asyncify_stop_unwind=function(){return(b._asyncify_stop_unwind=b.asm.u).apply(null,arguments)};
b._asyncify_start_rewind=function(){return(b._asyncify_start_rewind=b.asm.v).apply(null,arguments)};b._asyncify_stop_rewind=function(){return(b._asyncify_stop_rewind=b.asm.w).apply(null,arguments)};var X;function A(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}N=function Ja(){X||Ka();X||(N=Ja)};
function Ka(){function a(){if(!X&&(X=!0,b.calledRun=!0,!G)){P(ka);if(b.onRuntimeInitialized)b.onRuntimeInitialized();if(b.postRun)for("function"==typeof b.postRun&&(b.postRun=[b.postRun]);b.postRun.length;){var c=b.postRun.shift();la.unshift(c)}P(la)}}if(!(0<K)){if(b.preRun)for("function"==typeof b.preRun&&(b.preRun=[b.preRun]);b.preRun.length;)na();P(ja);0<K||(b.setStatus?(b.setStatus("Running..."),setTimeout(function(){setTimeout(function(){b.setStatus("")},1);a()},1)):a())}}b.run=Ka;
if(b.preInit)for("function"==typeof b.preInit&&(b.preInit=[b.preInit]);0<b.preInit.length;)b.preInit.pop()();Ka();
