platform:
  - x64
configuration:
  - Release
image:
  - 'Visual Studio 2017'
environment:
  VULKAN_SDK: c:\VulkanSDK\1.1.108.0
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      MSVC_SETUP_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
      MSVC_SETUP_ARG: x64
test: off

before_build:
  - 'set generator=Visual Studio 14 Win64'
  - 'set vcplatform=x64'
build_script:
  - 'CALL zbu4.bat'
  - 'CALL zbu5.bat'
skip_commits:
  message: '/.*\[skip appveyor\].*/'
after_build:
  - '7z a bina.zip %APPVEYOR_BUILD_FOLDER%\build-vs2017'
artifacts:
  -
    path: bina.zip
    name: Binari
