name: pod_push

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
    
      - name: Install Cocoapods
        run: gem install cocoapods
        
      - name: Deploy to Cocoapods
        run:
          pod spec lint --allow-warnings NCNN_IOS.podspec
          pod trunk push --allow-warnings NCNN_IOS.podspec
          pod spec lint --allow-warnings NCNN_MAC.podspec
          pod trunk push --allow-warnings NCNN_MAC.podspec
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}  
