name: pod_push

on:
  workflow_dispatch:
jobs:
  cocoapods:
    runs-on: macos-latest
    steps:
      - name: Install Cocoapods
        run: gem install cocoapods

  iOS:
    needs: [cocoapods]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy_to_Cocoapods
        run: |
          pod spec lint --allow-warnings NCNN_IOS.podspec
          pod trunk push --allow-warnings NCNN_IOS.podspec
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}

  MacOS:
    needs: [cocoapods]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to Cocoapods
        run: |
          pod spec lint --allow-warnings NCNN_MAC.podspec
          pod trunk push --allow-warnings NCNN_MAC.podspec
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}  
